# Generated by Django 3.2 on 2021-05-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210527_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='postreply',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
