# Generated by Django 3.2 on 2021-05-30 09:22

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderitem_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('payment_type', models.CharField(choices=[('Card', 'Card'), ('Privat24', 'Privat24'), ('GooglePay', 'GooglePay'), ('ApplePay', 'ApplePay'), ('PayPal', 'PayPal')], default='Card', max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_info', to='orders.order')),
            ],
        ),
    ]
