# Generated by Django 3.2 on 2021-04-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.CharField(choices=[('RPG', 'RPG'), ('Strategy', 'Strategy'), ('Action', 'Action')], default='Action', max_length=20),
        ),
    ]
