# Generated by Django 3.2 on 2021-05-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210517_0706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ('date_added',)},
        ),
        migrations.AddField(
            model_name='game',
            name='thumbnail',
            field=models.ImageField(default='null', upload_to='images/'),
            preserve_default=False,
        ),
    ]
