# Generated by Django 3.2 on 2021-05-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210517_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='images/thumbnails/'),
        ),
    ]
