# Generated by Django 3.2 on 2021-05-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_game_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
