# Generated by Django 3.2 on 2021-05-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_game_date_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ('added',), 'verbose_name_plural': 'games'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('name',), 'verbose_name_plural': 'genres'},
        ),
        migrations.RenameField(
            model_name='game',
            old_name='date_added',
            new_name='added',
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
