# Generated by Django 3.2 on 2021-05-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20210517_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(default='null', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
