# Generated by Django 3.2 on 2021-05-29 18:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_game_price'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='game',
            constraint=models.CheckConstraint(check=models.Q(price__gt=Decimal('0')), name='price_gt_0'),
        ),
    ]
